version: '3'
services:
  postgres:
    restart: always
    image: postgres:10
    environment:
      POSTGRES_USER: blackduck
      POSTGRES_PASSWORD: blackduck
      POSTGRES_DB: notifications
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  fetchnotifications:
    depends_on:
      - postgres
    image: jvalance/hub-timer-fetch:latest
    ports:
      - 5000:5000
    env_file: hub-config.env
    volumes:
      - .:/fetchnotifications
    environment:
      DATABASE_URL: postgres://blackduck@postgres/notifications
  reminder:
    depends_on:
      - postgres
    image: jvalance/hub-timer-reminder:latest
    ports:
      - "25:25"
      - "587:587"
    env_file: hub-config.env
    volumes:
      - .:/reminder
    environment:
      DATABASE_URL: postgres://blackduck@postgres/notifications
      