version: '3'
services:
  postgres:
    restart: always
    image: postgres:10
    environment:
      POSTGRES_USER: blackduck
      POSTGRES_PASSWORD: blackduck
      POSTGRES_DB: notifications
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  fetchnotifications:
    depends_on:
      - postgres
    build: ./fetchnotifications
    ports:
      - 5000:5000
    volumes:
      - .:/fetchnotifications
    environment:
      DATABASE_URL: postgres://blackduck@postgres/notifications
  reminder:
    depends_on:
      - postgres
    build: ./reminder
    environment:
      DATABASE_URL: postgres://blackduck@postgres/notifications
      