# Config file for Black Duck Hub and postgres
#
# Reminder to put 'token ' in front of auth token
blackduck:
    hubHost: "hubeval74.blackducksoftware.com"
    hubUserAuthToken: "token MDBjOWU1YjItOWE1OC00YTZiLWE4MzktOTE3MWZiMDg1YzI5OjQ3Y2Q3Y2VkLTg2N2YtNDI5Yy04Y2E2LTYwZWIwMDA5ZGQ3MQ=="
postgres:
    host: "postgres"
    dbname: "notifications"
    user: "blackduck"
    password: "blackduck"
reminder: '0 days'
email:
    sender: "valancejeremy@gmail.com"
    recipient: "valancejeremy@gmail.com"
    subject: "Black Duck Policy Violation Reminder"
    login: "valancejeremy@gmail.com"
    password: ""