# Config file for Black Duck Hub and postgres
#
# Reminder to put 'token ' in front of auth token
blackduck:
    hubHost: "hub.com"
    hubUserAuthToken: "token "
postgres:
    host: "postgres"
    dbname: "notifications"
    user: "blackduck"
    password: "blackduck"
reminder: '0 days'
email:
    sender: "gmail.com"
    recipient: "@gmail.com"
    subject: "Black Duck Policy Violation Reminder"
    login: "@gmail.com"
    password: ""