# Config file for Black Duck Hub and postgres
#
# Reminder to put 'token ' in front of auth token
blackduck:
    hubHost: "hubeval74.blackducksoftware.com"
    hubUserAuthToken: "token MDBjOWU1YjItOWE1OC00YTZiLWE4MzktOTE3MWZiMDg1YzI5OjIyY2Y3YTQzLTYwYTctNGQ1My05NWI5LWFiM2Q1MWRkYWRjZg=="
postgres:
    host: "postgres"
    dbname: "notifications"
    user: "blackduck"
    password: "blackduck"
reminder: "30"
email:
    sender: "valancejeremy@gmail.com"
    recipient: "valancejeremy@gmail.com"
    subject: "Black Duck Policy Violation Reminder"
    login: "valancejeremy@gmail.com"
    password: "password"